name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, zip, phar

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Build PHAR
        run: php cow app:build cow --build-version="${GITHUB_REF_NAME}" --no-interaction

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: builds/cow
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
